### ISSUE TITLE
No tags for Artist

### ISSUE THREAD

**Issue by brunakov** [MyerFire/lastfmpy#1]
`object.Artist` does not get populated with attributes besides `name`

Example code : 

```
api = await LastFM(API_KEY)
artist = "some_band"
similar_artists = await api.artists.get_similar(artist)
assert similar_artists[0].tags== []
```

**Comment by myerDOT** [comment]
this is not something i can do anything about due to last.fm api limitations
i should probably add this to readme, but the object attributes are populated to the extent of the data in the response itself
![image](https://user-images.githubusercontent.com/19848162/108578709-804ac280-72f1-11eb-8da7-9252ca310679.png)
this is the response if i ask for artists similar to `BLACKPINK`
as you can see, there is no tag field, meaning it would be impossible for it to be populated

**Comment by brunakov** [comment]
Ok. My comment was due to `object.Artist` having `tags` attribute. 
So [pylast](https://github.com/pylast/pylast) is getting tags by querying the API for each `'pylast.Artist'` ? For example :
```
pylast_artist = api.get_artist("BLACKPINK")
top_tags =pylast_artist.get_top_tags()
```
Is `get_top_tags()` a new query to the API?

**Comment by myerDOT** [comment]
yeah i would believe so, the source code suggests that it initiates a request
